---
title: Digilifetoday
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: taufiktw
    avatar: "assets/images/avatar3.jpg"
- scope:
    path: _pages
  values:
    layout: page
name: Digilifetoday
description: Let Us Talk About Digital Life .
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: "/"
disqus: taufiktw-github-io
email: taufiktw@gmail.com
mailchimp-list: https://mailchi.mp/282edcb69770/digilifetoday
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  taufiktw:
    name: taufiktw
    site: https://digilifetoday.com
    avatar: "/assets/images/avatar3.jpg"
    bio: Hi, I am Taufiktw, the author of Digilifetoday, I hope you like it!
    email: taufiktw@gmail.com
    twitter: https://twitter.com/digilifetod4ay
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
